config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: 'welcome#index'
    resources :payments,only:[:pay_tickets,:checkout] do
      collection do
        post'pay_tickets/:id/tickets/:tickets' => :pay_tickets,as: :pay_tickets
        get 'checkout' => :checkout,as: :checkout
      end
    end  
    resources :concerts do
      collection do
        get 'show_tickets/:id' => :show_tickets,as: :show_tickets
        get 'create_order_pay/:id'=> :create_order_pay,as: :create_order_pay
      end
    end
  end

  unauthenticated :user do
    root to:'welcome#unregistered'
    resources :concerts,only:[:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
# == Schema Information
#
# Table name: concerts
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  places      :integer
#  price       :decimal(10, 2)
#  slug        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_concerts_on_slug     (slug) UNIQUE
#  index_concerts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Concert < ApplicationRecord
  
  belongs_to :user
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  validates :name, :description, :places, :price, presence: true

  # method for get the total prince in cards
  def get_total(number_of_tickers)
  	self.price * number_of_tickers.to_i
  end
  # method for update the places in the concert
  def update_concert_tickets(tickets)
  	new_places = places - tickets
  	self.update(places: new_places)
  end
  #method for check if places are available in a concert
  def tickets_availables?
    self.places > 0
  end

end

app/models/my_payment.rb
# == Schema Information
#
# Table name: my_payments
#
#  id         :bigint           not null, primary key
#  email      :string
#  fee        :decimal(6, 2)
#  ip         :string
#  quantity   :integer
#  status     :string
#  total      :decimal(10, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  concert_id :bigint
#  paypal_id  :string
#  user_id    :bigint
#
# Indexes
#
#  index_my_payments_on_concert_id  (concert_id)
#  index_my_payments_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (concert_id => concerts.id)
#  fk_rails_...  (user_id => users.id)
#
class MyPayment < ApplicationRecord

  include AASM

  aasm column: 'status' do

    state :created, initial: true
    state :payed
    state :failed

    event :pay do 
      transitions from: :created, to: :payed
    end 
    
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :concerts

  def is_admin?
  	self.role == "admin"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy,
                                      :show_tickets, :create_order_pay]
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:create, :new, :update,
                                              :destroy, :index]
  def show_tickets 
  end

  def create_order_pay
    @number_of_tickets = params[:number_of_tickets]
  end

  def index
    @concerts = Concert.all
  end

  def show
  end

  def new
    @concert = Concert.new
  end

  def edit
  end

  def create
    @concert = current_user.concerts.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to concerts_path, notice: 'Concierto creado.'}
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concerts_path, notice: 'Concierto actualizado.'}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concierto eliminado.'}
    end
  end

  private

    def set_concert
      @concert = Concert.friendly.find(params[:id])
      @tickets = params[:tickets]
    end

    def authenticate_admin!
      if !current_user.is_admin?
        redirect_to root_path, 
          alert: 'no puedes realizar esta acción',status: :unauthorized 
      end
    end

    def concert_params
      params.require(:concert).permit(:name, :description, :places, :price)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :set_concert, only:[:pay_tickets]
  
  include PayPal::SDK::REST

  def pay_tickets
    payment = Payment.new({
      intent: 'sale',
      payer:{
        payment_method: 'paypal'
      },
      transactions:[
        {
          item_list:{
            items:[{name: 'boletos', sku: :item , price:(@concert.price / 100) , currency:'USD', quantity: @tickets  }]
          },
          amount:{
            total:(@concert.get_total(@tickets) / 100),
            currency:'USD'
          },
          description: 'compra de tus boletos en nuestra plataforma'
        }
      ],
      redirect_urls:{
        return_url: 'https://fast-savannah-49643.herokuapp.com/payments/checkout',
        cancel_url:  'https://fast-savannah-49643.herokuapp.com/'
      }
    })

    if @tickets.to_i > @concert.places
      redirect_to concerts_path,alert:'no hay la cantidad de boletos solicitados'
    else
      if payment.create
        @my_payment = MyPayment.create!(paypal_id: payment.id, ip: request.remote_ip, user_id: current_user.id,
          concert_id: @concert.id, quantity: @tickets)
        redirect_to payment.links.find{|v| v.method == 'REDIRECT'}.href
      else
        raise payment.error.to_yaml 
      end
    end
  end


  def checkout
    
    @my_payment = MyPayment.find_by(paypal_id: params[:paymentId]) 
    if @my_payment.nil? 
      redirect_to concerts_path
    else
      concert = Concert.find(@my_payment.concert_id)
      payment = Payment.find(@my_payment.paypal_id)
      if payment.execute(payer_id: params[:PayerID])
        concert.update_concert_tickets(@my_payment.quantity)
        @my_payment.pay!

        redirect_to concert_path(concert.id),notice: 'Ha comprado sus boletos exitosamente'
      else
        redirect_to concert_path(concert.id),alert: 'Hubo problemas al procesar su pago'
      end
    end
  end

  private
    def set_concert
      @concert = Concert.friendly.find(params[:id])
      @tickets = params[:tickets]
    end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_concerts
  def index
  end

  def unregistered
  end

  def set_concerts
    @concerts = Concert.all.order(name: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/concerts/_form.html.haml
= form_for @concert do |f|
  - if @concert.errors.any?
    #error_explanation
      %h2= "#{pluralize(@concert.errors.count, "error")} prohibited this concert from being saved:"
      %ul
        - @concert.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name,class:'form-control'
  .form-group
    = f.label :description
    = f.text_area :description,class:'form-control'
  .form-group
    = f.label :places
    = f.number_field :places,class:'form-control'
  .form-group
    = f.label :price
    = f.text_field :price,class:'form-control'
  .actions
    = f.submit 'Guardar',class:'btn btn-primary'

app/views/concerts/create_order_pay.haml
.row.justify-content-center
  .col-md-6.text-center
    %h1 Boletos reservados
    %table.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %th Concierto
          %th Numero de boletos
          %th Precio unitario
          %th Total
      %tbody
        %td= @concert.name
        %td= @number_of_tickets
        %td= number_to_currency(@concert.price, separator: ',', delimiter: '')
        %td= number_to_currency(@concert.get_total(@number_of_tickets), separator: ',', delimiter: '')
      
    .mt-5
      =render 'payments/buttons'

app/views/concerts/edit.html.haml
.row.justify-content-center
  .col-md-4
    %h1 Editar concierto

    = render 'form'
    .mt-5
      = link_to 'regresar', concerts_path

app/views/concerts/index.html.haml
%h1 Lista de conciertos
.mt-5.mb-5
  = link_to 'Agregar concierto', new_concert_path,class:"btn btn-primary"

%table.table.table-hover.table.striped
  %thead
    %tr
      %th Nombre
      %th Descripción
      %th Numero de boletos
      %th Precio
      %th
      %th
      %th

  %tbody
    - @concerts.each do |concert|
      %tr
        %td= concert.name
        %td= concert.description
        %td= concert.places
        %td=number_to_currency(concert.price, separator: ',', delimiter: '')
        %td= link_to 'Ver', concert
        %td= link_to 'Editar', edit_concert_path(concert)
        %td= link_to 'Eliminar', concert, method: :delete, data: { confirm: 'Are you sure?' }

app/views/concerts/new.html.haml
.row.justify-content-center
  .col-md-4
    %h1 Nuevo concierto

    = render 'form'
    .mt-5
      = link_to 'regresar', concerts_path

app/views/concerts/show.html.haml
.row.mt-5
  .col-md-6
    =image_tag 'concert.jpg',width:500
  .col-md-6

    %h2= @concert.name
    %p
      = @concert.description
    
    -if @concert.tickets_availables?
      %p
        %b Boletos disponibles:
        %br
        = @concert.places
      %p
        %b Costo por boleto:
        %br
        =number_to_currency(@concert.price, separator: ',', delimiter: '')
      .mt-5
        =link_to "Buscar boletos", show_tickets_concerts_path(@concert.slug),class:'btn btn-success' 
    -else 
      %h3 Boletos agotados

    -if current_user.is_admin?
      = link_to 'Edit', edit_concert_path(@concert)
      \|
      = link_to 'Back', concerts_path

app/views/concerts/show_tickets.haml
.row.justiy-content-center.mt-5
  .col-md-6
    =image_tag 'concert.jpg',width:500
  .col-md-6
    -if @concert.tickets_availables?
      %label Numero de boletos disponibles
      = @concert.places
      %br
      %label Costo por boleto
      =number_to_currency(@concert.price, separator: ',', delimiter: '')

      .mt-5
        = form_tag  create_order_pay_concerts_path(@concert.slug), method: :get,id:"search-form"  do
          .form-group
            %label Numero de boletos por comprar 
            %br
            = number_field_tag :number_of_tickets 
          .form-group
            = content_tag :button, type: :submit,class:'btn btn-success' do
              Comprar 
    -else
      %label boletos agotados
      %br
    
    
   

     

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Concerts
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'shared/navigation'
      = render 'shared/flash_messages'
      = yield

app/views/payments/_buttons.haml
= button_to pay_tickets_payments_path(@concert.slug,@number_of_tickets) , method: :post, class:'btn btn-success' do 
  Pagar 

app/views/shared/_concerts.haml
.row.justify-content-center
  %h1.mt-3.mb-5 Proximos conciertos
.row.justify-content-center
  -@concerts.each do |concert|
    .col-md-3
      .card{:style => "width: 18rem;"}
        =image_tag 'concert.jpg',class:'card-img-top'
        .card-body
          %h5.card-title=concert.name
          %p.card-text=concert.description
          -if concert.tickets_availables?
            =link_to 'Comprar boletos', concert, class:'btn btn-primary'
          -else
            %p Boletos agotados
          

app/views/shared/_flash_messages.haml
%p.large-padding.roboto.red.white-text.text-center.alert{:style => "#{'display:none;' if alert.nil?} margin-bottom: 0px;"}
  = alert
  %span.close-parent{:style => "float: right; cursor: pointer;"} X
%p.large-padding.roboto.blue.white-text.text-center.alert{:style => "#{'display:none;' if notice.nil?} margin-bottom: 0px;"}
  = notice
  %span.close-parent{:style => "float: right; cursor: pointer;"} X

app/views/shared/_navigation.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  =link_to 'Concerts', root_path , class:'navbar-brand' 
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item.active
        =link_to 'Inicio', root_path,class:'nav-link'
      -if user_signed_in?
        %li.nav-item
          -if current_user.is_admin? 
            =link_to 'Conciertos', concerts_path,class:'nav-link' 
        %li.nav-item
          =link_to 'Cerrar sesion', destroy_user_session_path, method: :delete, class:'nav-link'
      -else
        %li.nav-item
          =link_to 'Iniciar sesion',new_user_session_path,class:'nav-link'
        %li.nav-item
          =link_to 'Crear cuenta',new_user_registration_path,class:'nav-link'
      

app/views/welcome/index.haml
= render 'shared/concerts'

app/views/welcome/unregistered.haml
= render 'shared/concerts'